### ISSUE TITLE
Prestige Keeps crashing when loading Minecraft

### ISSUE THREAD

**Issue by FearowGaming** [JarHax/Prestige#26]
[crash-2020-09-27_14.27.01-client.txt](https://github.com/JarHax/Prestige/files/5288829/crash-2020-09-27_14.27.01-client.txt)
 
Dear Jaredlll08 and DarkhaxDev every time i load up my pack with prestige it's version 1.1.58 it crashes any ideas? Thanks

**Comment by OlafatheG** [comment]
me too

**Comment by jaredlll08** [comment]
Assuming it is the same issue, you have an invalid prestige file, it may have gotten corrupt, so delete it or redownload the modpack.

**Comment by OlafatheG** [comment]
I already done it , i clicked the unin00.exe file , after that i donwloaded
the louncher and pastet again my key in but It dont work/it crashes anyway

Jared ***@***.***> schrieb am So., 1. Mai 2022, 13:57:

**Comment by OlafatheG** [comment]
and I also have an Low end pc so maybe it could be my pc but the first time
I started the client worked well but now its just crashing

Jared ***@***.***> schrieb am So., 1. Mai 2022, 13:57:

**Comment by jaredlll08** [comment]
I have no idea what you are talking about with an exe file, we do not use exe files, you most likely uninstalled the launcher but not the modpack, so the invalid config file is still there.

**Comment by OlafatheG** [comment]
oh so how can i delete the ModPack? Is there were a folder is called
Prestige?

Jared ***@***.***> schrieb am So., 1. Mai 2022, 14:07:

**Comment by jaredlll08** [comment]
I don't know what launcher or what modpack you are using, you need to look up how to find the modpack folder for whatever launcher you're using, and then delete the `config/prestige/rewards.json` file

**Comment by OlafatheG** [comment]
Ok, thanks.


Jared ***@***.***> schrieb am So., 1. Mai 2022, 14:12:

**Comment by OlafatheG** [comment]
Oh and BTW Im using the Launcher "Provided"

Jared ***@***.***> schrieb am So., 1. Mai 2022, 14:12:
