### ISSUE TITLE
[Feature Request] Config or similar to make prestige points per world

### ISSUE THREAD

**Issue by Goldenlion5648** [JarHax/Prestige#3]
Prestige is awesome for having a points system without having to use items as currency, but I think it would be cool to be able to make prestige points per world. This way, easy quests could not be done over and over in different worlds to gain points

**Comment by Darkhax** [comment]
The entire point of the mod is that it allows for progress in a pack that is not tied to a world. Implementing your suggestion would defeat the entire purpose and goal of this mod. We also allow modpack authors to provide an optional source value when giving a player prestige points. Players can only gain points from a specific source once, which effectively allows for you to define quests as only being unlockable once.
