### ISSUE TITLE
Divide by Zero exception when opening Prestige window

### ISSUE THREAD

**Issue by justinrusso** [JarHax/Prestige#6]
When pressing 'P' to open Prestige, the game crashes.

Crash log: https://pastebin.com/gLgry0ht

Reference: https://github.com/Darkosto/SkyFactory4Issues/issues/217

**Comment by Novasae** [comment]
After updating I get the same crash when I press "change background"
Crash log: https://paste.ee/p/DJIjv

**Comment by jaredlll08** [comment]
That is because the update doesn't have the new version.

Try with this one https://minecraft.curseforge.com/projects/prestige/files/2699773

**Comment by Novasae** [comment]
I was already using the new version of the mod at this point.

**Comment by jaredlll08** [comment]
Using older versions doesn't help when reporting issues.

Are you still having an issue on the latest version on curseforge?
If yes, give me the log file.
