### ISSUE TITLE
Everyone in a server has perms for /prestige force

### ISSUE THREAD

**Issue by ApolloMCC** [JarHax/Prestige#8]
Everyone in a server has perms for /prestige force. Can you add a perm for it or a way to disable?

**Comment by jaredlll08** [comment]
Prestige force is used to sync the values from the server to the client, incase there is a desync.

Is there a problem with this, like are people abusing it or something?

**Comment by ApolloMCC** [comment]
No, prestige force enables/disables prestige for all players

**Comment by jaredlll08** [comment]
OH! okay scratch that, apparently I got my commands mixed up, yea that is a bug, and will be fixed in the next release!

**Comment by ApolloMCC** [comment]
Thank you jared

**Comment by ApolloMCC** [comment]
Would we be able to update the mod without players having to update their clients?

**Comment by jaredlll08** [comment]
I don't see a reason why that should be an issue :)
