### ISSUE TITLE
Server kicking most of the players while getting this error in console

### ISSUE THREAD

**Issue by ApolloMCC** [JarHax/Prestige#9]
Server kicks most of the players I checked console and this is the last thing that it logs before the massive kicks https://pastebin.com/5e9NqyEJ

**Comment by jaredlll08** [comment]
I'm going to need more info.

what happened before it crashed?

Using Sponge?


Any info that you think could be useful :)

**Comment by ApolloMCC** [comment]
Using sponge yes, I dont know what happened before since there are 50 players online. 
And it did not crash it just kicks people out
